language: node_js
node_js:
  - "20"

# Linux ve macOS için yapılandırmalar
os:
  - linux
  - osx

# Build işlemlerini her iki platformda da gerçekleştirin
jobs:
  include:
    - stage: build
      os: linux
      script:
        - npm i -g yarn
        - yarn install
        - yarn build
        - yarn package-linux
        - tar -czf releases/${VERSION}/linux-build.tar.gz -C releases/${VERSION} .
        - travis-artifacts upload --path releases/${VERSION}/linux-build.tar.gz

    - stage: build
      os: osx
      script:
        - npm i -g yarn
        - yarn install
        - yarn build
        - yarn package-macos
        - tar -czf releases/${VERSION}/macos-build.tar.gz -C releases/${VERSION} .
        - travis-artifacts upload --path releases/${VERSION}/macos-build.tar.gz

# Versiyon bilgisi ve artifact'lar
env:
  global:
    - VERSION=$(node -p "require('./package.json').version")
